global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'premium-spread-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api:9080']
  - job_name: 'premium-spread-batch'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['batch:9081']
