spring:
  data:
    redis:
      repositories:
        enabled: false
      redisson:
        pool-size: ${REDIS_POOL_SIZE:10}
        minimum-idle: ${REDIS_POOL_MIN_IDLE:2}
        retry-attempts: ${REDIS_RETRY_ATTEMPTS:3}
        retry-interval: ${REDIS_RETRY_INTERVAL:1500ms}
        command-timeout: ${REDIS_COMMAND_TIMEOUT:3s}
        connect-timeout: ${REDIS_CONNECT_TIMEOUT:10s}

---
spring.config.activate.on-profile: local

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: local-redis-password

---
spring.config.activate.on-profile: test

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: ""

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: qa

---
spring.config.activate.on-profile: prd

spring:
  data:
    redis:
      host: ${REDIS_MASTER_HOST}
      port: ${REDIS_MASTER_PORT}
      password: ${REDIS_PASSWORD}
