version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    container_name: premium-spread-api
    environment:
      SPRING_PROFILES_ACTIVE: prd
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: application
      MYSQL_PWD: application
      REDIS_MASTER_HOST: redis-master
      REDIS_MASTER_PORT: 6379
      REDIS_REPLICA_1_HOST: redis-readonly
      REDIS_REPLICA_1_PORT: 6379
    restart: unless-stopped
    networks:
      - premium-spread

  batch:
    build:
      context: ..
      dockerfile: apps/batch/Dockerfile
    container_name: premium-spread-batch
    environment:
      SPRING_PROFILES_ACTIVE: prd
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: application
      MYSQL_PWD: application
      REDIS_MASTER_HOST: redis-master
      REDIS_MASTER_PORT: 6379
      REDIS_REPLICA_1_HOST: redis-readonly
      REDIS_REPLICA_1_PORT: 6379
    restart: unless-stopped
    networks:
      - premium-spread

  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
    container_name: premium-spread-web
    environment:
      NEXT_PUBLIC_API_URL: /api/v1
    restart: unless-stopped
    networks:
      - premium-spread

  nginx:
    image: nginx:alpine
    container_name: premium-spread-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - api
      - web
    restart: unless-stopped
    networks:
      - premium-spread

networks:
  premium-spread:
    external: true
    name: premium-spread
