services:
  batch:
    build:
      context: ..
      dockerfile: apps/batch/Dockerfile
    container_name: premium-spread-batch
    environment:
      SPRING_PROFILES_ACTIVE: prd
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: application
      MYSQL_PWD: application
      REDIS_MASTER_HOST: redis-master
      REDIS_MASTER_PORT: 6379
      REDIS_REPLICA_1_HOST: redis-readonly
      REDIS_REPLICA_1_PORT: 6379
    restart: unless-stopped
    networks:
      - premium-spread

networks:
  premium-spread:
    external: true
    name: premium-spread
