services:
  batch:
    build:
      context: ..
      dockerfile: apps/batch/Dockerfile
    container_name: premium-spread-batch
    environment:
      SPRING_PROFILES_ACTIVE: prd
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PWD: ${MYSQL_PWD}
      REDIS_MASTER_HOST: redis-master
      REDIS_MASTER_PORT: 6379
      REDIS_REPLICA_1_HOST: redis-readonly
      REDIS_REPLICA_1_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      EXCHANGE_RATE_API_KEY: ${EXCHANGE_RATE_API_KEY}
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      ALERT_EMAIL_FROM: ${ALERT_EMAIL_FROM}
    restart: unless-stopped
    networks:
      - premium-spread

networks:
  premium-spread:
    external: true
    name: premium-spread
