#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
quality_workflow="${root_dir}/.github/workflows/quality-gate.yml"
deploy_workflow="${root_dir}/.github/workflows/deploy.yml"
tool_lock="${root_dir}/ci/quality-tools.lock"

fail() {
  echo "quality gate contract failed: $*" >&2
  exit 1
}

workflow_job_block() {
  local job="$1"
  awk -v job="${job}" '
    $0 == "  " job ":" { inside = 1 }
    inside && $0 ~ /^  [a-z0-9-]+:$/ && $0 != "  " job ":" { exit }
    inside { print }
  ' "${quality_workflow}"
}

deploy_workflow_job_block() {
  local job="$1"
  awk -v job="${job}" '
    $0 == "  " job ":" { inside = 1 }
    inside && $0 ~ /^  [a-z0-9-]+:$/ && $0 != "  " job ":" { exit }
    inside { print }
  ' "${deploy_workflow}"
}

for script in "${root_dir}"/ci/*.sh; do
  bash -n "${script}"
done

[[ -f "${quality_workflow}" ]] || fail "quality-gate.yml is missing"
grep -q 'pull_request:' "${quality_workflow}" || fail "pull request trigger is required"
grep -q 'refactor/infrastructure-boundary' "${quality_workflow}" || fail "refactor branch push trigger is required"
grep -q 'workflow_dispatch:' "${quality_workflow}" || fail "manual SHA trigger is required"
grep -q 'description: Commit SHA to verify' "${quality_workflow}" || fail "manual dispatch must accept an explicit SHA"
grep -q 'TARGET_SHA:.*github.event.inputs.sha.*github.sha' "${quality_workflow}" || fail "all triggers must resolve an explicit candidate SHA"
[[ "$(grep -c 'run: bash ci/verify-target-sha.sh' "${quality_workflow}")" -eq 7 ]] ||
  fail "all seven required jobs must validate checkout HEAD against the candidate SHA"
grep -q '\^\[0-9a-fA-F\]{40}\$' "${root_dir}/ci/verify-target-sha.sh" || fail "manual candidate SHA must be 40-hex"
grep -q 'git rev-parse HEAD' "${root_dir}/ci/verify-target-sha.sh" || fail "checked out HEAD must be verified"

expected_jobs=(compile-architecture unit-coverage api-integration batch-integration static-analysis dependency-security docker-build)
for job in "${expected_jobs[@]}"; do
  grep -q "^  ${job}:$" "${quality_workflow}" || fail "required job ${job} is missing"
done
actual_jobs="$(grep -Ec '^  (compile-architecture|unit-coverage|api-integration|batch-integration|static-analysis|dependency-security|docker-build):$' "${quality_workflow}")"
[[ "${actual_jobs}" -eq 7 ]] || fail "quality gate must define exactly seven required job IDs"

while IFS= read -r use; do
  ref="${use##*@}"
  [[ "${ref}" =~ ^[0-9a-f]{40}$ ]] || fail "action is not SHA-pinned: ${use}"
done < <(rg -o 'uses: [^ ]+@[^ ]+' "${root_dir}/.github/workflows")

grep -q 'bash ci/bootstrap-quality-tools.sh --verify-checksums' "${quality_workflow}" || fail "checksum bootstrap is required"
grep -q 'detekt-cli.jar' "${quality_workflow}" || fail "standalone detekt is required"
grep -q -- '--config config/detekt/detekt.yml' "${quality_workflow}" || fail "standalone detekt configuration is required"
grep -q -- '--baseline config/detekt/baseline.xml' "${quality_workflow}" || fail "detekt baseline contract is required"
grep -q 'ktlint.jar' "${quality_workflow}" || fail "standalone ktlint is required"
grep -q 'run-dependency-check.sh' "${quality_workflow}" || fail "dependency-check wrapper is required"
grep -q -- '--failOnCVSS 7' "${root_dir}/ci/run-dependency-check.sh" || fail "CVSS 7 dependency-check threshold is required"
grep -q 'run-npm-audit.sh' "${quality_workflow}" || fail "web audit gate is required"
grep -q 'npm --prefix apps/web run lint' "${quality_workflow}" || fail "locked web lint gate is required"
grep -q 'npm --prefix apps/web ci --include=optional' "${quality_workflow}" || fail "web install must include locked native optional dependencies"
grep -q 'npm ci --include=optional' "${root_dir}/apps/web/Dockerfile" || fail "web image must include locked native optional dependencies"

grep -q 'id: verification-metadata' "${quality_workflow}" || fail "compile job must detect committed verification metadata"
[[ "$(grep -c "if: steps.verification-metadata.outputs.committed == 'false'" "${quality_workflow}")" -eq 3 ]] ||
  fail "missing metadata must have bootstrap, artifact publication, and fail-closed steps"
[[ "$(grep -c 'resolveVerificationArtifacts --write-verification-metadata sha256 --no-daemon' "${quality_workflow}")" -eq 2 ]] ||
  fail "root and build-logic verification metadata must both be generated by isolated CI resolvers"
grep -q './gradlew -p build-logic resolveVerificationArtifacts --write-verification-metadata sha256 --no-daemon' \
  "${quality_workflow}" || fail "build-logic requires its own verification artifact resolver"
grep -q 'tasks.register("resolveVerificationArtifacts")' "${root_dir}/build-logic/build.gradle.kts" ||
  fail "build-logic verification artifact resolver task is missing"
grep -q 'name: gradle-verification-metadata-${{ env.TARGET_SHA }}' "${quality_workflow}" ||
  fail "verification metadata artifact must be bound to the immutable candidate SHA"
grep -q 'gradle/verification-metadata.xml && -f build-logic/gradle/verification-metadata.xml' "${quality_workflow}" ||
  fail "root and build-logic verification metadata must both be committed"
grep -q '^            gradle/verification-metadata.xml' "${quality_workflow}" || fail "root verification metadata must be published"
grep -q '^            build-logic/gradle/verification-metadata.xml' "${quality_workflow}" ||
  fail "build-logic verification metadata must be published"
grep -q 'Require metadata review and a follow-up commit' "${quality_workflow}" || fail "bootstrap run must require review and a follow-up commit"
grep -q 'exit 1' "${quality_workflow}" || fail "uncommitted verification metadata must fail closed"
for dependent_job in unit-coverage api-integration batch-integration dependency-security docker-build; do
  job_line="$(grep -n "^  ${dependent_job}:$" "${quality_workflow}" | cut -d: -f1)"
  sed -n "${job_line},$((job_line + 5))p" "${quality_workflow}" | grep -q 'needs: compile-architecture' ||
    fail "${dependent_job} must wait for strict compile/bootstrap verification"
done
while IFS= read -r gradle_command; do
  [[ "${gradle_command}" == *"--write-verification-metadata"* ]] && continue
  [[ "${gradle_command}" == *"--dependency-verification strict"* ]] ||
    fail "committed-metadata Gradle gate is not explicitly strict: ${gradle_command}"
done < <(rg 'run: ./gradlew' "${quality_workflow}")

api_job="$(workflow_job_block api-integration)"
batch_job="$(workflow_job_block batch-integration)"
api_integration_command='run: ./gradlew :infrastructure:common:verifyMigrations :infrastructure:common:integrationTest :apps:api:integrationTest --dependency-verification strict --no-daemon'
batch_integration_command='run: ./gradlew :apps:batch:integrationTest --dependency-verification strict --no-daemon'
grep -Fq "${api_integration_command}" <<< "${api_job}" ||
  fail "api-integration job must execute the exact strict API/common integration tasks"
grep -Fq "${batch_integration_command}" <<< "${batch_job}" ||
  fail "batch-integration job must execute the exact strict Batch integration task"

compile_contract='compileKotlin architectureTest verifyTestIsolationPolicy verifyCoverageExclusions :build-logic:test --dependency-verification strict'
grep -q "${compile_contract}" "${quality_workflow}" ||
  fail "required compiler, architecture, isolation, exclusion and build-logic gates must execute together"
grep -Fq 'include("test.exec")' "${root_dir}/build.gradle.kts" ||
  fail "unit coverage must consume only unit-test execution data"
if grep -Fq 'include("*.exec")' "${root_dir}/build.gradle.kts"; then
  fail "unit coverage must not absorb stale integration execution data"
fi
for contract_command in \
  'bash ci/quality-gate-contract-test.sh' \
  'bash ci/local-offline-contract-test.sh' \
  'bash docs/check-documentation.sh' \
  'bash docker/deploy-contract-test.sh'; do
  grep -q "${contract_command}" "${quality_workflow}" || fail "required CI contract is not executed: ${contract_command}"
done

grep -q 'run: ./gradlew prepareDependencyCheckInput --dependency-verification strict --no-daemon' "${quality_workflow}" ||
  fail "OWASP scan must stage strict-verified runtime artifacts"
grep -q 'prepareDependencyCheckInput' "${root_dir}/ci/stage-dependency-check-input.sh" ||
  fail "external production runtime dependency JAR staging is required"
grep -q 'externalArtifactsOf(runtimeProjects' "${root_dir}/build.gradle.kts" ||
  fail "dependency-check input must resolve API/Batch external runtime artifacts"
grep -q -- '--dependency-verification strict' "${root_dir}/ci/stage-dependency-check-input.sh" ||
  fail "runtime JAR staging must use strict dependency verification"
grep -q 'build/dependency-check-input' "${root_dir}/ci/stage-dependency-check-input.sh" ||
  fail "runtime JAR staging directory is missing"
grep -q -- '--scan "${input_dir}"' "${root_dir}/ci/run-dependency-check.sh" ||
  fail "Dependency-Check must scan only staged production runtime JARs"
if grep -q -- '--scan "${root_dir}"' "${root_dir}/ci/run-dependency-check.sh"; then
  fail "Dependency-Check must not scan the repository source tree"
fi
grep -q -- '--data "${data_dir}"' "${root_dir}/ci/run-dependency-check.sh" ||
  fail "Dependency-Check must use its isolated NVD data directory"
grep -q 'dependency_data_dir=.*dependency-check-data' "${root_dir}/ci/bootstrap-quality-tools.sh" ||
  fail "bootstrap must create a separate dependency data directory"
if rg -n 'rm -rf.*dependency-check-data|rm -rf[[:space:]]+"\$\{(tool_dir|dependency_data_dir)\}"' \
  "${root_dir}/ci/bootstrap-quality-tools.sh"; then
  fail "tool bootstrap must never delete cached Dependency-Check data"
fi
grep -q 'path: .ci-tools/dependency-check-data' "${quality_workflow}" || fail "NVD data must be cached separately"
grep -q 'dependency-check-data-${{ runner.os }}' "${quality_workflow}" || fail "NVD data cache key is missing"
if grep -q '^          path: \.ci-tools$' "${quality_workflow}"; then
  fail "tool installation cache must not absorb the isolated NVD data directory"
fi

docker_job="$(workflow_job_block docker-build)"
[[ "$(grep -c 'outputs: type=docker,dest=${{ runner.temp }}/docker-images/' <<< "${docker_job}")" -eq 3 ]] ||
  fail "Docker job must export API, Batch and Web as loadable archives"
for component in api batch web; do
  grep -Fq "tags: ghcr.io/\${{ github.repository }}/${component}:\${{ env.TARGET_SHA }}" <<< "${docker_job}" ||
    fail "Docker ${component} archive must carry the immutable candidate tag"
  grep -Fq "outputs: type=docker,dest=\${{ runner.temp }}/docker-images/${component}.tar" <<< "${docker_job}" ||
    fail "Docker ${component} archive output is missing"
done
grep -Fq 'name: docker-images-${{ env.TARGET_SHA }}' <<< "${docker_job}" ||
  fail "Docker archives must be uploaded as a candidate-SHA artifact"
grep -Fq 'path: ${{ runner.temp }}/docker-images/*.tar' <<< "${docker_job}" ||
  fail "Docker archive artifact path is missing"
for dockerfile in "${root_dir}/apps/api/Dockerfile" "${root_dir}/apps/batch/Dockerfile"; do
  gradle_lines="$(grep 'RUN ./gradlew' "${dockerfile}")"
  [[ -n "${gradle_lines}" ]] || fail "${dockerfile} must contain Gradle build steps"
  while IFS= read -r gradle_line; do
    [[ "${gradle_line}" == *"--dependency-verification strict"* ]] ||
      fail "container Gradle resolution is not explicitly strict: ${gradle_line}"
  done <<< "${gradle_lines}"
  grep -q 'COPY gradle gradle' "${dockerfile}" ||
    fail "container dependency layer must receive committed verification metadata"
  grep -q 'gradle.properties gradle.lockfile ./' "${dockerfile}" ||
    fail "container dependency layer must receive the root dependency lock"
  grep -q 'COPY build-logic build-logic' "${dockerfile}" ||
    fail "container dependency layer must receive build-logic lock and verification metadata"
  locked_projects=(
    apps/api apps/batch architecture-tests domain
    infrastructure/common infrastructure/api infrastructure/batch
    modules/jpa modules/redis
    supports/email supports/logging supports/monitoring
  )
  for locked_project in "${locked_projects[@]}"; do
    grep -q "${locked_project}/gradle.lockfile" "${dockerfile}" ||
      fail "container dependency layer is missing ${locked_project}/gradle.lockfile"
  done
done

lock_entries="$(grep -Evc '^#|^[[:space:]]*$' "${tool_lock}")"
[[ "${lock_entries}" -eq 3 ]] || fail "ktlint, detekt and dependency-check must all be locked"
while IFS='|' read -r name version url sha; do
  [[ -z "${name}" || "${name}" == \#* ]] && continue
  [[ -n "${version}" && "${url}" == https://* && "${sha}" =~ ^[0-9a-f]{64}$ ]] ||
    fail "invalid checksum lock entry for ${name}"
done < "${tool_lock}"
ktlint_property="$(sed -n 's/^ktLintVersion=//p' "${root_dir}/gradle.properties")"
detekt_property="$(sed -n 's/^detektVersion=//p' "${root_dir}/gradle.properties")"
ktlint_locked="$(awk -F'|' '$1 == "ktlint" { print $2 }' "${tool_lock}")"
detekt_locked="$(awk -F'|' '$1 == "detekt" { print $2 }' "${tool_lock}")"
[[ -n "${ktlint_property}" && "${ktlint_property}" == "${ktlint_locked}" ]] ||
  fail "ktlint version must have one value across gradle.properties and the checksum lock"
[[ -n "${detekt_property}" && "${detekt_property}" == "${detekt_locked}" ]] ||
  fail "detekt version must have one value across gradle.properties and the checksum lock"

publish_job="$(deploy_workflow_job_block publish-images)"
grep -q 'workflow_run:' "${deploy_workflow}" || fail "deploy must consume the completed quality workflow"
grep -q 'github.event.workflow_run.conclusion == .success.' <<< "${publish_job}" || fail "deploy must require successful quality gate"
grep -q 'github.event.workflow_run.head_branch == .main.' <<< "${publish_job}" || fail "deploy must accept protected main only"
grep -q 'github.event.workflow_run.event == .push.' <<< "${publish_job}" || fail "deploy must accept main push only"
grep -q 'environment: production' "${deploy_workflow}" || fail "deploy must use the approval-protected production environment"
grep -Fq 'DEPLOY_SHA: ${{ github.event.workflow_run.head_sha }}' "${deploy_workflow}" ||
  fail "deploy SHA must be the exact successful workflow head SHA"
grep -q '^  actions: read$' "${deploy_workflow}" || fail "deploy needs read access to Quality Gate artifacts"
if grep -q 'DEPLOY_SHA:.*||' "${deploy_workflow}"; then
  fail "deploy SHA must not have a fallback"
fi
grep -Fq 'name: docker-images-${{ env.DEPLOY_SHA }}' <<< "${publish_job}" || fail "deploy must download the exact candidate artifact"
grep -Fq 'run-id: ${{ github.event.workflow_run.id }}' <<< "${publish_job}" || fail "deploy artifact must come from the successful workflow run"
grep -q 'docker load --input' <<< "${publish_job}" || fail "deploy promotion must load the verified image archive"
grep -q 'docker push "${image}"' <<< "${publish_job}" || fail "deploy promotion must push the loaded verified image"
if rg -n 'docker/build-push-action|docker build|setup-buildx-action' "${deploy_workflow}"; then
  fail "deploy must promote Quality Gate archives without rebuilding"
fi
[[ "$(grep -c 'run: bash ci/verify-target-sha.sh' "${deploy_workflow}")" -eq 2 ]] ||
  fail "image publication and deployment must both verify the quality-gated SHA"

if rg -n 'org\.jlleitschuh\.gradle\.ktlint|io\.gitlab\.arturbosch\.detekt|org\.owasp\.dependencycheck' \
  "${root_dir}" --glob '*.gradle' --glob '*.gradle.kts' --glob 'settings.gradle*'; then
  fail "CI-only quality/security tools must not participate in Gradle resolution"
fi

echo "quality gate and supply-chain contracts verified"
