build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: true
  checkExhaustiveness: false

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 100
    excludes: ['**/src/test/**', '**/src/integrationTest/**', '**/src/architectureTest/**', '**/src/testFixtures/**']
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 12
    ignoreDefaultParameters: true
    ignoreDataClasses: true
    ignoreAnnotatedParameter: ['ConfigurationProperties']
    excludes: ['**/src/test/**', '**/src/integrationTest/**', '**/src/architectureTest/**', '**/src/testFixtures/**']
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20
    excludes: ['**/src/test/**', '**/src/integrationTest/**', '**/src/architectureTest/**', '**/src/testFixtures/**']

coroutines:
  active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames: ['Error', 'RuntimeException', 'Throwable']
    allowedExceptionNameRegex: '_|(ignore|expected).*'

potential-bugs:
  active: true

style:
  active: true
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 140
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
    excludes: ['**/src/test/**', '**/src/integrationTest/**', '**/src/architectureTest/**', '**/src/testFixtures/**']
  ReturnCount:
    active: true
    max: 4
    excludedFunctions: ['equals']
    excludeLabeled: false
    excludeReturnFromLambda: true
    excludeGuardClauses: true
